sudo: required
dist: trusty
language: node_js
node_js:
  - stable
branches:
  except:
    - gh-pages
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script: yarn add polymer-cli
script:
  - xvfb-run polymer test --module-resolution=node --npm --skip-plugin sauce
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --module-resolution=node --npm --plugin sauce --skip-plugin local; fi'
after_success:
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET" -in deploy.enc -out deploy_key -d; fi'
  - cd $TRAVIS_BUILD_DIR/scripts
  - chmod 755 ghp.sh
  - ./ghp.sh
env:
  global:
    - secure: ax0Nr8HJnj0KS67r7CCFUnVZ/SSrn27i+CswL3Y97Q8R4tZMegLR7jLo1OymA8rfJ/ehb5usR06+7UhjEZeQ+7yToF9Sb+Hq/nRe4Ia0wlEb1OCxH0uKIzJm/zvsE/da/LwNDi4fVzyNjEvEIGjsbB3c1THDg4q4JRrjxxkLp5VGSRpAfD2K/Bpn42rxwJjNtFDtbgf+gBvckQAzo0qIyQwklAeeVBUw7LyxpAdTlYJtJsdFb13dhxXNJi3mDlhcypdtP3CY/6HgkEd1pthF7AFll0bz95O9A/RYGgMk6bV0ODUE5Kpa0RIZ2F/73x4CiJWMZ8W+ojMHAJcBE7MWFdVSACxVoW3/pY4E8VNJHuMXjSRRbO66ojubLhDmVvmpFd/rEcCg+C4Re+LZxWFV9pFi2gscg4D/lvGPOD2Yz9BxJasLEnDJMFCPHA6atjkNIRcvQv5AiGzOzrNclZodgIe4xRKEj2MEMqtkkUzLa5nOYOAG9laoczec9HL5/C+jm6epopFNQnL9c2bgck0kWoF3NSLyYk9kkbitk/HJMuEyDVfdy5JzECgfaT9MbFQl0NM7Ml+ToRVaK4d0xxQTPJc6TmE7QrUANjRcvhP5+LLCCf8C6xLukqGU3afFNKwH2cIFd/eW7JNwQrIhQZEO1vrgpx9ueVG9ik/wtM7Pkc8=
    - secure: uGFl6RFfRSjrWFhRNj66VhKCOOF+SKA6MIytA6TJJBT0k/WdRWuvnebkmLKpno77eoQQaIaD9uWm0yY2d5W5/ejRMpG/9yJjmVx5yN1vdLUu3EbfTGOCImzkhKfH5/bznhVs7KT2uuA4lxuiwWXP8KR0DsoCNO5XW5AYEgY4F5CR8GSZ2HXwivMfKBnylouFcpGmFsB4jRoG4UvVMnJIiV4O5KdklZwqxKnKNa/9GKqg8yonMLfDNUTe7E5w9tvgBfVzh4AeN6rnc+NlsSvpycGnQaQDbzsdTgkJNnlLqYevabUddissqj2yFqTqpuaziBcffm256e0dQMV7GjVCmUaKc6FOD9Uu37gTaW7tu20zmhT0WEeH41MLxFvULEBOw0HKNJLM7rozNvwxfH1vwu1wXx7PDO7jI4KFhvMY1aOpiNxDjoJ7DgEZYdBLlYV4bqOVmC1a3kz7hokbrz3nB/yE5w08b+T5UGyHjJZRNF6uy5lS6GpypMiMmCTST/jegFROVT03bbEWWNIlFYqANx2pgFI47wLXNY/6RYpeRVRVp//gxFejbADtEO1t6KMfOKXnHfLbaDiRrUcGtaLj1cMrev2yYMGJttuvgskZc2VJaEd0nhDcWROST6Vvde9ZdDnHE6q2Va/vIxYgs4k3hzOKioRg3ZGwPyw837SN6tI=
    - secure: L3J0AylMdAy7DGUPlTzI1Gf3kgrL6NpUz46YAM1Z/WxLexkn9r3IbpV5KAdPXmkQBLpxtvxF+6t3U91j6R/rkCDv3K7Ph9oYR3Il9uqd6CVgOK7703EhSIWZxZ430It0gjNbBaqLINo4KlVT8alULzYINvsn6M7XIWkwPFrqM6Zm2ZvfpBl2fwMDeXDTp/nkPDljkhZL/UmwXQHvF7fTUGOZvs7eXMKkhGHyNcnuWEE7CqPoCjWoaQXJAaHpRAZfwdZV2IGb3u1MEamgqHecr/Li6soBJ/gx574i+nptwl690sTDwbDZidnbHwUd3hWhN3VYGHj3NGxAqWYDa2IgifSZRL+gY6Lshd0cTsDhY+d6vxxX2lK0LGGThJ6MyqxkNAu4fIuDG/YqnuoYkYxV0okhU16NULfOgHDv0FAZvc0qNJ7fCQb6gNSwbjUdgYnfw+OOgzvAVZrCL0jss2bIGUSaOyOpLLMfU3MKbxfbDbGP900ORhINT8Sl73Cxha5b8wZNA4Wz1osYvmGq1U9aeGOYylaS2Uyhdi5/OWoiUv3p4fjPjgcUoRnz+YcqmWduXeCyKMn2Yrpm8e1DfrBphbxlKg1xGVjzWCs+30LdD7zQH1el8P9vSr4SYeGSmnG/cxGmWHNF+vhWhYvkZVbcdADnBfkJC4VjUMutpQYqnJY=
    - secure: mmWsktRAtaapoAfSTXczKqVwXhFsR66UBcojyTXcs9mxhhP7WHCx+aGXXctKSS812hWhTrdQRsTqPKl4yK+gdPZbsVLiucWT0oyxZPOETV1knivN/u5gx0UmJz2x2Bx49gTlhO6wUuc/Oft9Reo67vqt2tC1Vsg+uprsTtWud/QNgY5DXuOE5Hr5dsMT0o1KRZXw0qOcLo8lnQ3TZpba7Df4y1RLtCApooHWyI8q/ywvs5b6ojDf4gAGDpWBpHvr4oYA6z8dt0h4kuE9FsKBoIovnXgchjoYEQbmUth0dvYp3Fpv6Yf81YDvfzI17MX6DwnkV6MW5l6HYU7TpEXc7GKOt1gUhIWDy0P+n7YdLhdzbzd1Zm1VM71VQKg7s3cfEAwNVgQukG18TLWUnUSE7lEIeSUaUbkmqdjdHc/0hpvVpjLebmpVn6Zg3Yhu3dzxmJy1KOWx3KyhweKeCMY4ESD1vsYfCrFkoGbcU5cy8pGuZRS7vWdNAj9bRuoQaryu7GJafDssvRycTj1kr9HW8MSwVfaQ0r4QugHhPDEnE79iQktk4EcfopDwmU0hi1ohNH8hc4bC823UreFw/U652L8ddL/mbQgCtWexYS2YUSk2CSHieSNJC16jZzM+cRcJIUCFlfzkNo50skfCmEucso7rKsrRDh8VMCQUy/QT2Ns=

