sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: ax0Nr8HJnj0KS67r7CCFUnVZ/SSrn27i+CswL3Y97Q8R4tZMegLR7jLo1OymA8rfJ/ehb5usR06+7UhjEZeQ+7yToF9Sb+Hq/nRe4Ia0wlEb1OCxH0uKIzJm/zvsE/da/LwNDi4fVzyNjEvEIGjsbB3c1THDg4q4JRrjxxkLp5VGSRpAfD2K/Bpn42rxwJjNtFDtbgf+gBvckQAzo0qIyQwklAeeVBUw7LyxpAdTlYJtJsdFb13dhxXNJi3mDlhcypdtP3CY/6HgkEd1pthF7AFll0bz95O9A/RYGgMk6bV0ODUE5Kpa0RIZ2F/73x4CiJWMZ8W+ojMHAJcBE7MWFdVSACxVoW3/pY4E8VNJHuMXjSRRbO66ojubLhDmVvmpFd/rEcCg+C4Re+LZxWFV9pFi2gscg4D/lvGPOD2Yz9BxJasLEnDJMFCPHA6atjkNIRcvQv5AiGzOzrNclZodgIe4xRKEj2MEMqtkkUzLa5nOYOAG9laoczec9HL5/C+jm6epopFNQnL9c2bgck0kWoF3NSLyYk9kkbitk/HJMuEyDVfdy5JzECgfaT9MbFQl0NM7Ml+ToRVaK4d0xxQTPJc6TmE7QrUANjRcvhP5+LLCCf8C6xLukqGU3afFNKwH2cIFd/eW7JNwQrIhQZEO1vrgpx9ueVG9ik/wtM7Pkc8=
  - secure: uGFl6RFfRSjrWFhRNj66VhKCOOF+SKA6MIytA6TJJBT0k/WdRWuvnebkmLKpno77eoQQaIaD9uWm0yY2d5W5/ejRMpG/9yJjmVx5yN1vdLUu3EbfTGOCImzkhKfH5/bznhVs7KT2uuA4lxuiwWXP8KR0DsoCNO5XW5AYEgY4F5CR8GSZ2HXwivMfKBnylouFcpGmFsB4jRoG4UvVMnJIiV4O5KdklZwqxKnKNa/9GKqg8yonMLfDNUTe7E5w9tvgBfVzh4AeN6rnc+NlsSvpycGnQaQDbzsdTgkJNnlLqYevabUddissqj2yFqTqpuaziBcffm256e0dQMV7GjVCmUaKc6FOD9Uu37gTaW7tu20zmhT0WEeH41MLxFvULEBOw0HKNJLM7rozNvwxfH1vwu1wXx7PDO7jI4KFhvMY1aOpiNxDjoJ7DgEZYdBLlYV4bqOVmC1a3kz7hokbrz3nB/yE5w08b+T5UGyHjJZRNF6uy5lS6GpypMiMmCTST/jegFROVT03bbEWWNIlFYqANx2pgFI47wLXNY/6RYpeRVRVp//gxFejbADtEO1t6KMfOKXnHfLbaDiRrUcGtaLj1cMrev2yYMGJttuvgskZc2VJaEd0nhDcWROST6Vvde9ZdDnHE6q2Va/vIxYgs4k3hzOKioRg3ZGwPyw837SN6tI=
  - secure: QhtynbiGEaXPGBux2oDhgEtfRhgMM9c7vj111ItKKQv/FCA5bBW73hCrRTW76eLTn2HSheTPB1FNDWJ0o3c7uy//K2YMb/fS1pS39J81ayzeCfucsux3EJsj6ZRggy+zJzaa0LO8+q2qHCNDArFPBmradfGmsKUt35BQIAS11Z482rFlaobMWrz6q/ly9/oq7naSFEJ4OuJflR4WjbRNnsUskzeH4hOALTxAJ1UJRvZi8wk/zjObv4V7nkcRXrqNpeBrYZ8z3rYPI9T0+lrGymng5yqomoOpB6J1hI2hENghjX5q4ndKxJP6s+VfOvFjR3XPfQBqdS7bhRcnBFiiKC62WG/ND8p5kfHtR8+1fL6iyi848yqzBkkOarzSTJcCgUV9hfmVsHQmJ8O0EdSB+1riKt+cPzolnA0SsIOWkv6vV0NhlLtKYtl8AKQPEhpyXzEI196pc0M0VRv5nUDD2ukQVKyzbvdD9dqsP+khZYuIaJSlQ7aiO6pzKIU7uwwxnhDTBm0td48NMM7gqH2X4z6KSSTVFHXiTWuIcWLcmmNel9y0J1ZD9TRbSxprXW/9QfuGs3GCINulG9xtIl1iG9ky8bvlV7ya/uW8nlQigq63U/O8/ZHpqy3t63nraQoflVljdy/Cdcqxni7S/OZEp4yswdKDmdqhM86DU5Ntj58=
