sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
    secure: BGBUy4mHpbldE9zcKoXGTyNa3mHPQ6P3yqrbmfNAZl2OXj/39IlIIVP7s389tIvSeUri/PNaOnCnzE1H1ALhRj2SPvneKye9LvnETsKpOlKoJxhK1P5Px5ah7TBl7FbkgCKQ15P+fBhWktbxZOHpOwjh/0yPaefdMvYAEMklwMjD3NR6vwhodm4Dpfc0xq2F1CvBAGLN42eUTETuEL8J9FtJiTv43d6FDzTvnkn5IWS0ncbJ0rkxdJm7FBk2UKWtAUY+26D5V9scznWmAN36MIm6YZKBW8y9kuij4xHTfmpbqFt4BgfWFlsPZgzgF1WAolNfTRTEcVCK/l28T3Pa30Z3NY8rSOF6TGIidsDPu91aMoHN5WtKOEFHVyVX1QOVUElFFRbtOK0xWPBeoCR7CMJ0oAhrgZNl4U+ZGjl85cOt3b3Abr26SI/JYBxpe2AoliAhx8SxEkT4jn8nDWyOKUVURNbsBP1LWspNEfiaMNAJsU4Ss9a2entfV/tGGIYCgUQ+QE8SefiNYbIISbPOCNqT2VCgJRUvuHpIc9IqZDUatcZ2q8VuredwIf5BgZrvrhWtaHqSQ9nrMeOw5keHuybvBV7A/abvrgqOfjt9+TfuNV0rDZWgROzA2yL4NuU1giL2ntcZMauz+Rys8FUGSfObX47xW1J0rbQN/1V3DeE=
    secure: d3ovOWMg9lnntG/D647Iv+AP+eb9AI5mxChSSyrLzwZ45YmX13Tya26gWu5jDU6V9HdGNgC5v7UtRGjZphcFHcj6l8MHo1dI07hkl4LOJdxksJrU4xA3Bts5PZV2cE0DlMVhc/OgQDNwGy0tGYPjN91KOZ/gKlIU88G0q7GTysJPy6r/XfCkcBxOXe32+/ho0YVklo3gkGWQzDJMjwmlS9oRYBQgC5oEOZhRI3GuEsDuFrC9UMAY9ckYD93+XBgGQAPi+YPaS3Xsx/gqt2PJQgNhvXd4q04K6phZg4ZTPqPaXd7qYdK+1xPo1rlZ/1mq/fDaWZiD+IIERe7b8ZHWGlEpppUbcV+9k0SSh2ZDQGMr7tIt+xweeWmO2REsNQIwnvTmt21BFqdt97nLbyw5lbIpveG0vW334xz2oP3nI1YdBTMgx3EDk7QmE8Pmu1vYP5td9+L1lT35wp1O/9UJQMJ+YskxA/vOjD8NYlKUtXP0Jq8ztRsrFHmYMURM+3XZQllFz7RcA9lh+pOZwa//h4gpGxG1xNwVP1+L/+BaO+6RsOYEHnJRr0crKqOCNdxgxcPdN+DRsFJSz2f6dlqWXpKczb2wVLbyalNcda41p84hzCNHE6mM72VtYp/RK1yRSMCRuNIOs2mmBLNZM8CzmHBT+QemBuvONMkJ3SMEbA4=
before_install:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password" -in id_rsa.enc -out deploy_key -d; fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
