sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: WjVxPpW+IBgKtq82pCPEKlcacuNi9uGAvfkY5zfGhBTSdzUxw/G3SeLKzXiRvhW653s75DxlO6ngyZ6lbc6afBz/88QlVpxBN5qTYUG17QsaJlEJhNOKMJgni4EgX2+6q1inn6kqELsO9b/ETlMCPDFcpWZdfivZ4HlNplOZ9/+BKi263WCTiCZTDdSN19IRpOxQJtBLqv81rDLKFatOkvH7NBneLuJD7yaIZ314Ktw11SUPmXTrbrqW8VQVi6WuQnvH3Y/RUqswoQMDcVqh0oipJgtdN7X+oltrMF1L0yM0AXn1frYs8WOISBQIkRAUDHVkN8q+0xoPmgZY74ZHYKR1SBYrW9QSCi4WJwQBPm/AvspC3ao3xpWbS3TWoZ+a63VoUi3aAzqQy8Ue6266g37pHM3+sdnum4yIGjWi8yxIZRK9mG7QwOm3ANH4MFcQnrOyD7z6J6JzIXYgldNgqkapOfQk0YNSmAeYrk1ClfCAnmGkoYYs6FF+y4DFk+E4hlnLhsvEtJ/KoKlmRWW5MR5B422wH3qKzLYdXv2oxC7QiiYmChXrdC8xVQQkw7zYpxa+Wtr7nkgpJLryj5BPMgRVKsjj1GIx4qPS3m5pQr0f7Fth9On+BvBr4VDpBWvBFWrv6P3pRilw1z0XH9BM2dljLhict45xHmCsmsp6E9M=
  - secure: VfsvWZ7SdTJjgt33fy8PHNCogpu0PTR7BEwLgtPM8+bAvcfCYvHHmDhebvha6mcm0tt4ZVIqgYyscQw9Dmwv1sC6E4sA5Z58LMpiAPWhfg34bGvuIy7DpzagmOiDKOyTQGJRMz/ztw6dKyxCoYOh5e8qI1YzgSIu9tS59x/IJgyk9/AkzKfGKbZxIjyXMVvm/TdkAF1CgCSHlBhAVSqp49LDIJ0I0KQfOOp3NeVqSLazaNtK0daPFiagp3ZqMTBR/hty2CoUY/cHCfFJZlwn7GGzzsJjx+gwL9HUWEupUtyo6ACdEPY/LsFkNLRjnrznkElBykot0pQ2OA1InqG2UI8TQVhcsNQl5sZYdYYBS/TAxwwVSfmX+13i8FGhJGORMGzE2v1Y2b9rd5U0wAae3PEfHbOx2/JfxULyv4IPMISOkOgnBPDn9OQDBQoODTP770P2ua3ODAEw5uKZ2uy1N89QJAVrPgnoLEwjTupZNuM/UVNolbQWU7NU1FJMEvaPlKlsx7/QkpyheZcugoGMdmXsWy6Kv1FT/T6kPZyzSS9aKwedaPTrY8kN/Rr7/58Bj2AjCFNrFFUzgqfi5UFvTfCIr4ZcWDvdywg0MYMtrlbRSXkxC5wfmZYjhdCgRjkhtgurAm3Eyyde6joyreffbpzC0csaIpEPDHa+0c9xIRI=
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- ./ghp.sh
